---
- name: Checking to make sure postfix is installed
  become: yes
  apt:
    name:
    - postfix
    - mailutils
    - ca-certificates
    - curl
    - openssh-server
    state: present
  tags: [postfix]
  when: ansible_os_family == 'Debian'

- name: Install GitLab repository
  become: yes
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /tmp/script.deb.sh
    mode: 0777

- name: Run GitLab repository script
  become: yes
  shell: /tmp/script.deb.sh

- name: Install GitLab CE
  become: yes
  package:
    name:
    - gitlab-ce
    state: latest
    update_cache: yes

- name: Run ufw allow http script
  become: yes
  command: ufw allow http

- name: Run ufw allow https script
  become: yes
  command: ufw allow https

- name: Run ufw allow OpenSSH script
  become: yes
  command: ufw allow OpenSSH

- name: Restart with reconfigure
  become: yes
  command: gitlab-ctl reconfigure

- name: GitLab Restart with restart
  become: yes
  command: gitlab-ctl restart

- name: GitLab gitlab-runsvdir status
  become: yes
  command: service gitlab-runsvdir status
